### ISSUE TITLE
Add --unsafe-retry-last-block CLI flag

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmos-sdk#6]
# Context

When an upgrade fails due to a consensus failure, or for some other reason a validator causes is out of consensus (ex. running the wrong binary), it is sometimes useful to be able to revert the last committed block.

# Acceptance Criteria

Given a user needs to revert a block
When they invoke their daemon with the `--unsafe-retry-last-block` (ex. `xrnd start --unsafe-retry-last-block`)
Then the state of the last committed block will be reverted and the daemon will try to reprocess that block

**Comment by ethanfrey** [comment]
Similar to #5 but definitely goes in the command level - this must be run before mounting the iavl store and needs no app logic

TODO: @ethanfrey provide demo script to reverse last block from sdk application

**Comment by sahith-narahari** [comment]
I feel this should go into cosmos-sdk/server,lot of applications may need to reset state in unexpected situations.We had such issue once in cosmos Game of Stakes.
@ethanfrey any opinions.?

**Comment by ethanfrey** [comment]
Yes, this should be a completely independent PR from the upgrade module.
And yes, inside `cosmos-sdk/server`.

I am split between `server run --unsafe-retry-last-block` and `server unsafe-rollback-block && server run`. The first is simpler, but only handles a one block rollback and immediate restart. The second is two commands, but you could rollback one or more blocks and then restart later. Not sure if there is a good use for that, but wanted to bring it up.

@aaronc thoughts?

**Comment by clevinson** [comment]
ping @aaronc, can you follow up here?

**Comment by clevinson** [comment]
Closing as most dev work is happening actively on cosmos/cosmos-sdk
